### ISSUE TITLE
do not work

### ISSUE THREAD

**Issue by vyalekseev** [swkim01/webiopi-dht#1]
![2](https://cloud.githubusercontent.com/assets/17781704/13700434/f0d73916-e791-11e5-849b-0bbcb1ddfd79.png)
Hi, I do not work, what could be wrong? sensor DHT22

**Comment by swkim01** [comment]
Did you configure webiopi to enable dht sensor? I modified README.md file. Please read it again.

**Comment by vyalekseev** [comment]
When I add the line 
"dht0 = DHT22 pin:18 " 
ceases to be loaded web page.

**Comment by vyalekseev** [comment]
Now log debug script and config

`File "/home/pi/myproject/python/script.py", line 20, in loop
    celsius = dht.getCelsius() # get current temperature
AttributeError: 'NoneType' object has no attribute 'getCelsius'

2016-03-16 13:40:37 - WebIOPi - ERROR - [Errno 98] Address already in use
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/WebIOPi-0.7.1-py3.4-linux-armv7l.egg/webiopi/protocols/http.py", line 45, in **init**
    BaseHTTPServer.HTTPServer.**init**(self, ("", port), HTTPHandler)
  File "/usr/lib/python3.4/socketserver.py", line 429, in **init**
    self.server_bind()
  File "/usr/lib/python3.4/http/server.py", line 133, in server_bind
    socketserver.TCPServer.server_bind(self)
  File "/usr/lib/python3.4/socketserver.py", line 440, in server_bind
    self.socket.bind(self.server_address)
OSError: [Errno 98] Address already in use
`
